SS_SetSoundVol(global.music1,global.musicvol2)
SS_SetSoundVol(global.music2,global.musicvol2)
SS_SetSoundVol(global.music3,global.musicvol2)
SS_SetSoundVol(global.music4,global.musicvol2)
SS_SetSoundVol(global.music5,global.musicvol2)
SS_SetSoundVol(global.music6,global.musicvol2)
SS_SetSoundVol(global.music7,global.musicvol2)
SS_SetSoundVol(global.music,global.musicvol2)
